### ISSUE TITLE
drop off

### ISSUE THREAD

**Issue by MnnGFng** [GaryDu0123/Apex_Stat_for_Hoshino#1]
请问这个报错是什么意思 ERROR:'drop off' occur when process command 查询当前地图 in apex

**Comment by GaryDu0123** [comment]
Hi, 感谢您的反馈~

检查了一下, 是因为map_names.py里面的地图名和api没有对应上导致的, 因为插件采用了两个api, 一个api的原料厂名字为Drop-Off 一个为Drop Off, 名字对应不上导致的错误, 为了解决这个错误, 有两种方法
1. 直接复制更新的代码里面的`map_names.py` 和 `get_map.py`到`modules/Apex Stat for Hoshino`插件工作目录下(建议)
(get_map.py添加了一些逻辑, 在往后名字对应不上时会显示api返回的英文)
3. 在`map_names.py`里面的`map_name_dict_config`改为
```python
map_name_dict_config = {
    "br": {
        "Olympus": "奥林匹斯",
        "World's Edge": "世界尽头",
        "Storm Point": "风暴点",
        "Kings Canyon": "诸王峡谷"
    },
    "arena": {
        "Phase Runner": "相位穿梭器",
        "Party Crasher": "派对破坏者",
        "Overflow": "溢出",
        "Encore": "再来一次",
        "Habitat 4": "栖息地4",
        "Habitat": "栖息地4",
        "Drop-Off": "原料厂",
        "Drop Off": "原料厂"
    }
}
```
(添加`"Drop Off": "原料厂`)

**Comment by GaryDu0123** [comment]
#350fd7ae0c35521fbea03aa7a0e45228f3177c11
