### ISSUE TITLE
收到消息后报错

### ISSUE THREAD

**Issue by qianxuu** [GaryDu0123/Apex_Stat_for_Hoshino#2]
![image](https://user-images.githubusercontent.com/62287903/175830285-d8904c82-f9fe-4947-b5b7-e42adca40bc6.png)

**Comment by GaryDu0123** [comment]
可以提供一下hoshino的版本号吗, 我在我本地的`hoshino/trigger.py`的代码里面找不到这行代码`event.message = oldmsg`, 代码在最新的hoshino里面是可以正常运行的
![image](https://user-images.githubusercontent.com/66729711/175874121-dcd29932-3bed-44fe-a39a-9b0cb8b6ee86.png)

**Comment by GaryDu0123** [comment]
其他的命令可以正常触发吗? 还是只有这一个无法运行
我在本地测试是可以正常查询的
![image](https://user-images.githubusercontent.com/66729711/175877242-cec30b32-add8-47e8-9834-1581333c3355.png)

**Comment by qianxuu** [comment]
> 其他的命令可以正常触发吗? 还是只有这一个无法运行
> 我在本地测试是可以正常查询的
> ![image](https://user-images.githubusercontent.com/66729711/175877242-cec30b32-add8-47e8-9834-1581333c3355.png)
> 
> 

都不行，都是这个报错

**Comment by GaryDu0123** [comment]
让我再确认几点:
1. 您的bot有运行其他插件吗, 其他的插件使用命令可以正常运行吗?
2. 再者在bot启动期间的时候有什么奇怪的输出或者报错吗?
3. Bot是在加入这个插件之后出现的问题吗, 移除后还会报错吗?

因为这看起来并不像是来自插件本身的错误
> 之所以做这个推断的原因是我将消息的触发函数设置为了`only_to_me=True`, 也就是说命令必须以`@bot + 命令`或者`bot- name + 命令`的形式触发, 看起来您使用了`apex 查询猎杀分数线`来触发, 理论上是不会被message_handler接收到函数内处理的( 并且 logger 也没有显示 `Message xxxx triggered process_command`), 所以我怀疑是来自其他插件或者环境的冲突

非常感谢您的反馈~

**Comment by qianxuu** [comment]
> 让我再确认几点:
> 
> 1. 您的bot有运行其他插件吗, 其他的插件使用命令可以正常运行吗?
> 2. 再者在bot启动期间的时候有什么奇怪的输出或者报错吗?
> 3. Bot是在加入这个插件之后出现的问题吗, 移除后还会报错吗?
> 
> 因为这看起来并不像是来自插件本身的错误
> 
> > 之所以做这个推断的原因是我将消息的触发函数设置为了`only_to_me=True`, 也就是说命令必须以`@bot + 命令`或者`bot- name + 命令`的形式触发, 看起来您使用了`apex 查询猎杀分数线`来触发, 理论上是不会被message_handler接收到函数内处理的( 并且 logger 也没有显示 `Message xxxx triggered process_command`), 所以我怀疑是来自其他插件或者环境的冲突
> 
> 非常感谢您的反馈~

1. 有其他插件，其他插件能正常运行
2. 启动时没有报错
3. 是收到这个插件的命令才会报错，移除后自然不会报错（

**Comment by GaryDu0123** [comment]
wwww, 我从咖啡佬的仓库内重新拉取的了最新的代码, 还是无法复现你的错误 (寄
![image](https://user-images.githubusercontent.com/66729711/175921870-1deae791-e015-408c-b090-16764425e6fd.png)
![image](https://user-images.githubusercontent.com/66729711/175921443-0f009794-509e-49d5-aff1-559aaac9049d.png)
试试保存副本然后更新下hoshino源码? 或者尝试在您的本地debug一下, 要是找到了问题还麻烦pr一下...

**Comment by qianxu2001** [comment]
> 

看到你说要 @ 机器人，试了一下确实没问题了，可以正常使用，不 @ 直接发才会有那个错误（

**Comment by qianxuu** [comment]
> > 之所以做这个推断的原因是我将消息的触发函数设置为了`only_to_me=True`, 也就是说命令必须以`@bot + 命令`或者`bot- name + 命令`的形式触发, 看起来您使用了`apex 查询猎杀分数线`来触发, 理论上是不会被message_handler接收到函数内处理的( 并且 logger 也没有显示 `Message xxxx triggered process_command`), 所以我怀疑是来自其他插件或者环境的冲突


才发现需要 @ 机器人，试了一下确实没问题了，可以正常使用，不 @ 直接发才会有那个错误（

**Comment by GaryDu0123** [comment]
OK 问题解决了就好
